@base_url = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create-account
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "Jefferson Lacerda",
  "email": "jeff@test.com",
  "password": "123456"
}

###
# @name authenticate
POST {{base_url}}/sessions
Content-Type: application/json

{
  "email": "jeff@test.com",
  "password": "123456"
}

###
# @name create-athlete
POST {{base_url}}/athletes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "jeff@test.com",
  "password": "123456"
}